// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateWindow(arg1, arg2) {
  return window['go']['main']['App']['ActivateWindow'](arg1, arg2);
}

export function CancelSwitcher() {
  return window['go']['main']['App']['CancelSwitcher']();
}

export function ConfirmSelection() {
  return window['go']['main']['App']['ConfirmSelection']();
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetDesktopSnapshot() {
  return window['go']['main']['App']['GetDesktopSnapshot']();
}

export function MoveSelection(arg1) {
  return window['go']['main']['App']['MoveSelection'](arg1);
}

export function RefreshWindows() {
  return window['go']['main']['App']['RefreshWindows']();
}

export function RequestAccessibilityPermission() {
  return window['go']['main']['App']['RequestAccessibilityPermission']();
}

export function RequestScreenRecordingPermission() {
  return window['go']['main']['App']['RequestScreenRecordingPermission']();
}

export function ShowSwitcher() {
  return window['go']['main']['App']['ShowSwitcher']();
}
