// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ActivateWindow(arg1:number,arg2:string):Promise<boolean>;

export function CancelSwitcher():Promise<void>;

export function ConfirmSelection():Promise<boolean>;

export function GetAppState():Promise<main.AppState>;

export function GetDesktopSnapshot():Promise<main.DesktopSnapshot>;

export function MoveSelection(arg1:number):Promise<main.DesktopSnapshot>;

export function RefreshWindows():Promise<main.DesktopSnapshot>;

export function RequestAccessibilityPermission():Promise<main.PermissionStatus>;

export function RequestScreenRecordingPermission():Promise<main.PermissionStatus>;

export function ShowSwitcher():Promise<main.DesktopSnapshot>;
